services:  
  frontend:
    build:
      context: ./Frontend
      dockerfile: DockerfileFrontend
    container_name: eventos-frontend
    ports:
      - "5173:5173"    
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=false
      - NODE_OPTIONS=--max-old-space-size=128
      - NPM_CONFIG_FUND=false
      - NPM_CONFIG_AUDIT=false
      - VITE_HMR_HOST=0.0.0.0
    depends_on:
      - backend
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 180M
          cpus: '0.2'
        reservations:
          memory: 120M

  backend:
    build:
      context: ./Backend
      dockerfile: DockerfileBackend
    container_name: eventos-backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
      - backend_vendor:/app/vendor
      - backend_uploads:/app/public/uploads    
    environment:
      - DATABASE_URL=mysql://IsmaCar:secret@database:3306/events
      - APP_ENV=prod
    depends_on:
      - database
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 160M
          cpus: '0.3'
        reservations:
          memory: 100M

  database:
    image: mysql:8.0
    container_name: eventos-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: events
      MYSQL_USER: IsmaCar
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password --innodb-buffer-pool-size=24M --max-connections=3 --innodb-log-file-size=8M --innodb-flush-log-at-trx-commit=2 --skip-innodb-doublewrite --innodb-flush-method=O_DIRECT --table-open-cache=32 --thread-cache-size=1 --key-buffer-size=4M --read-buffer-size=32K --sort-buffer-size=32K --tmp-table-size=8M --max-heap-table-size=8M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      timeout: 45s
      retries: 20
      interval: 20s
      start_period: 180s
    deploy:
      resources:
        limits:
          memory: 350M
          cpus: '0.4'
        reservations:
          memory: 250M

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: eventos-phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      PMA_USER: IsmaCar
      PMA_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
      MEMORY_LIMIT: 32M
      MAX_EXECUTION_TIME: 15
      MAX_INPUT_VARS: 500
      UPLOAD_LIMIT: 4M
      PMA_QUERYHISTORYMAX: 10
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 80M
          cpus: '0.1'
        reservations:
          memory: 48M
  web:
    build:
      context: ./nginx
      dockerfile: DockerfileWeb
    container_name: eventos-web
    ports:
      - "8020:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - frontend
      - backend
      - phpmyadmin
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 80M
          cpus: '0.1'
        reservations:
          memory: 48M

networks:
  app-network:
    driver: bridge

volumes:
  database_data:
  backend_vendor:
  backend_uploads: