services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: DockerfileFrontend
    container_name: eventos-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=false
    depends_on:
      - backend
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M

  backend:
    build:
      context: ./Backend
      dockerfile: DockerfileBackend
    container_name: eventos-backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
      - backend_vendor:/app/vendor
      - backend_uploads:/app/public/uploads
    depends_on:
      - database
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M

  database:
    image: mysql:8.0
    container_name: eventos-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: events
      MYSQL_USER: IsmaCar
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password --innodb-buffer-pool-size=64M --max-connections=10 --innodb-log-file-size=32M --innodb-flush-log-at-trx-commit=2 --skip-innodb-doublewrite
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 384M
          cpus: '0.5'
        reservations:
          memory: 192M

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: eventos-phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      PMA_USER: IsmaCar
      PMA_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
      MEMORY_LIMIT: 64M
      MAX_EXECUTION_TIME: 30
      MAX_INPUT_VARS: 1000
      UPLOAD_LIMIT: 8M
      PMA_QUERYHISTORYMAX: 25
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.2'
        reservations:
          memory: 64M

  web:
    build:
      context: ./nginx
      dockerfile: DockerfileWeb
    container_name: eventos-web
    ports:
      - "8020:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - frontend
      - backend
      - phpmyadmin
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.2'
        reservations:
          memory: 64M

networks:
  app-network:
    driver: bridge

volumes:
  database_data:
  backend_vendor:
  backend_uploads: